name: "Android Build and Release"

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build:
    name: Build Signed APK
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Set up JDK 17"
        uses: actions/setup-java@v1
        with:
          java-version: "17"
          distribution: "temurin"

      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2

      # 🔥 Regenerate Gradle Wrapper (Fix Gradle issue)
      - name: "Regenerate Gradle Wrapper"
        run: |
          ./gradlew wrapper
          chmod +x gradlew

      # 🔥 Automatically create a keystore (if missing)
      - name: "Generate Keystore"
        run: |
          if [ ! -f "app/debug.keystore" ]; then
            keytool -genkey -v -keystore app/debug.keystore -alias debug -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Debug, OU=Dev, O=MyApp, L=City, ST=State, C=US"
          fi

      - name: "Create Signing Config"
        run: |
          echo "storeFile=debug.keystore" >> $GITHUB_ENV
          echo "storePassword=android" >> $GITHUB_ENV
          echo "keyAlias=debug" >> $GITHUB_ENV
          echo "keyPassword=android" >> $GITHUB_ENV

      - name: "Build Signed APK"
        run: ./gradlew assembleRelease --no-daemon

      - name: "Find Generated APKs"
        run: |
          echo "APK_PATH=$(find app/build/outputs/apk/release -name '*.apk' -print | head -n 1)" >> $GITHUB_ENV

      - name: "Upload APK as Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: "Signed APK"
          path: app/build/outputs/apk/release/*.apk

      - name: "Create GitHub Release"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: "This is an automated release of the Android app."
          files: app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
