name: "Android Build and Release"

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build:
    name: Build Signed APK
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Set up JDK 17"
        uses: actions/setup-java@v1
        with:
          java-version: "17"
          distribution: "temurin"

      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2

      # 🔥 Ensure Gradle Wrapper Exists
      - name: "Check Gradle Wrapper"
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "Gradle Wrapper missing! Generating..."
            gradle wrapper
          fi

      # 🔥 Generate a Keystore for Signing (if not using a production keystore)
      - name: "Generate Keystore"
        run: |
          keytool -genkey -v -keystore app/debug.keystore -alias debug -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Debug, OU=Dev, O=MyApp, L=City, ST=State, C=US"

      # 🔥 Set up Signing Properties
      - name: "Create Signing Config"
        run: |
          echo "storeFile=debug.keystore" >> $GITHUB_ENV
          echo "storePassword=android" >> $GITHUB_ENV
          echo "keyAlias=debug" >> $GITHUB_ENV
          echo "keyPassword=android" >> $GITHUB_ENV

      - name: "Give Execute Permission to Gradle"
        run: chmod +x gradlew

      # 🔥 Build Signed APK
      - name: "Build Signed APK"
        run: ./gradlew assembleRelease --no-daemon

      # 🔥 Find the generated APK
      - name: "Find Generated APK"
        run: |
          echo "APK_PATH=$(find app/build/outputs/apk/release -name '*.apk' -print | head -n 1)" >> $GITHUB_ENV

      # 🔥 Upload the APK as an artifact
      - name: "Upload APK as Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: "Signed APK"
          path: app/build/outputs/apk/release/*.apk

      # 🔥 Create a GitHub Release
      - name: "Create GitHub Release"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: "This is an automated release of the Android app."
          files: app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
